
/*
 * Main.eq
 * Generated by Eqela Studio 2.0b7.4
 */

public class Main : LayerWidget
{
	public void initialize() {
		base.initialize();
		set_draw_color(Color.instance("black"));
		set_size_request_override(px("60mm"), px("80mm"));
		add(CanvasWidget.for_color(Color.instance("white")));
		add(LabelWidget.for_string("Widget application"));
	}

	public void cleanup() {
		base.cleanup();
	}
}
